### ISSUE TITLE
Display participant details based on CSV or API

### ISSUE THREAD

**Issue by tinok** [dighr/data-flood#11]
Data is hosted on airtable.com. Ideally we would pull relevant fields directly through the [Airtable API](https://airtable.com/api).

**Comment by tinok** [comment]
Fields to be displayed are
1. Name
2. Organization
3. Profile link
4. Bio
5. Picture

**Comment by richardt22** [comment]
Airtable Node.js code can't run on GitHub Pages and Amazon S3 as they don't support server-side code. I found another way to get the list of names. See https://github.com/dighr/data-flood#airtable-to-javascript

Result: https://dighr.github.io/data-flood/participant/

**Comment by tinok** [comment]
~~Not sure if it's because the API key has been changed, but the participant list fails to load at the moment~~

I just realized the error is nothing related to Airtable but just the misleading 404 error page from the main navigation that isn't pointing to `/participant` but `/participant`.

Please fix the navigation link :)

**Comment by tinok** [comment]
For now please include two fields from **all** participants marked as Attending: 
* Full_name
* Organization_cleaned

**Comment by richardt22** [comment]
added
