### ISSUE TITLE
Font size is too big

### ISSUE THREAD

**Issue by tinok** [dighr/data-flood#15]
At the moment the default font size of 16px is stretched to 22+px when viewing the page on a large screen. It should stay fixed to 16px (max).

**Comment by richardt22** [comment]
Are you referring to the EMERGENCY DATA SCIENCE heading? I tried 16px and it is too small.
https://ibb.co/g0ttfV

Is it the paragraph tags?

**Comment by tinok** [comment]
It's the paragraph text. And only when viewing on a large screen:

![image](https://user-images.githubusercontent.com/673511/49031101-1295a780-f177-11e8-891e-00e7a1a3e289.png)


Reopening.

**Comment by richardt22** [comment]
I made the paragraph elements font-size 16px.
