### ISSUE TITLE
Improve header titles

### ISSUE THREAD

**Issue by tinok** [dighr/data-flood#19]
The title background color should be 50% grey for all three titles, see example below. There should be a small padding around the text elements. Please use classes and CSS for the items instead of inline styles.

```
   background-color: rgba(0,0,0,.5);
    padding: 0 6px;
```

![image](https://user-images.githubusercontent.com/673511/48812862-40579800-ed02-11e8-86ea-afdebec604ce.png)

**Comment by richardt22** [comment]
updated
