### ISSUE TITLE
Password Protected Website

### ISSUE THREAD

**Issue by richardt22** [dighr/data-flood#8]
Working: d2hyhnit1e4g1k.cloudfront.net
guest:test

But with a glitch that bypasses auth login: http://data-flood.s3-website-us-east-1.amazonaws.com

**Comment by tinok** [comment]
@richardt22 Could you document the steps taken to require authentication via Cloudfront? 

I suspect that direct S3 access can be disabled through a policy/setting for the S3 bucket somehow, but not a priority at the moment. Please close this when the documentation is up.

**Comment by richardt22** [comment]
documentation added
